# @package _global_

defaults:
  - base

loader:
  _target_: scaleretarget.loader.mixamo_loader.MixamoLoader
  _recursive_: False
  config:
    loader_type: mixamo
    data_format: .bvh

    use_optimized_shape: True
    optim_joint_matches: config/correspondence/optim_shape/${loader.config.loader_type}_to_${robot.robot_type}.yaml
    optim_iterations: 3000